<a href="https://colab.research.google.com/github/Siddharth131020/dsa/blob/main/numpie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(5,)

In [5]:
b= np.array([[1],[2],[3],[4],[5]])

In [6]:
type(b)

numpy.ndarray

In [7]:
b.shape

(5, 1)

In [8]:
a = np.zeros((3, 3), dtype = int)

In [9]:
a.shape

(3, 3)

In [10]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
#b = np.one((3, 3))
b = np.ones((3, 3))


In [12]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
c = np.full((3, 3), 2, dtype=float)

In [14]:
c

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [15]:
np.full?

In [16]:
d = np.eye(4)
#identity matrix

In [17]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye?

In [19]:
rnt_mat = np.random.random((3,3))

In [20]:
rnt_mat

array([[0.80193807, 0.56531842, 0.34572023],
       [0.55182691, 0.57238746, 0.20164713],
       [0.32056841, 0.6601319 , 0.55730387]])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [22]:
x + y


array([[ 6,  8],
       [10, 12]])

In [23]:
x - y


array([[-4, -4],
       [-4, -4]])

In [24]:
x*y


array([[ 5, 12],
       [21, 32]])

In [25]:
x/y


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [26]:
print(np.add(x, y))


[[ 6  8]
 [10 12]]


In [27]:
print(np.subtract(x, y))


[[-4 -4]
 [-4 -4]]


In [28]:
print(np.multiply(x, y))


[[ 5 12]
 [21 32]]


In [29]:
print(np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [30]:
np.sqrt(144)


12.0

In [31]:
print(np.matmul(x, y))


[[19 22]
 [43 50]]


In [32]:
print(np.dot(x, y))


[[19 22]
 [43 50]]


In [33]:
x.dot(y)


array([[19, 22],
       [43, 50]])

In [34]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])

In [35]:
b=b**2

In [36]:
b

array([ 1,  4,  9, 16, 25, 36])

In [37]:
a=np.stack((a,b),axis=0)

In [38]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  4,  9, 16, 25, 36]])

In [39]:
b

array([ 1,  4,  9, 16, 25, 36])

In [40]:
a.T

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [41]:
a.reshape((6, 2))


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [42]:
a.reshape((4, 3))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  4,  9],
       [16, 25, 36]])

In [43]:
a.reshape((3, 4))


array([[ 1,  2,  3,  4],
       [ 5,  6,  1,  4],
       [ 9, 16, 25, 36]])

In [44]:
a.reshape((-1, 4))


array([[ 1,  2,  3,  4],
       [ 5,  6,  1,  4],
       [ 9, 16, 25, 36]])

In [45]:
a = np.arange(10)


In [46]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a+=5


In [48]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
np.random.shuffle(a)


In [50]:
a

array([14,  6, 13,  9,  5,  8, 12, 10,  7, 11])

In [51]:
a = np.random.rand(2, 3)


In [52]:
a

array([[0.81575717, 0.51036776, 0.81878002],
       [0.22319961, 0.0790284 , 0.73099637]])

In [53]:
np.random.randint(5, 100, (5, 5))


array([[43, 34, 32,  5, 92],
       [77, 39, 46, 78, 19],
       [63, 97, 61,  8, 97],
       [81, 94, 30, 39,  5],
       [36, 78, 48, 87, 97]])

In [54]:
print(np.mean(c))


2.0


In [56]:
print(np.arange(3, 20, 3))


[ 3  6  9 12 15 18]


In [57]:
np.random.shuffle(a)


In [58]:
a = np.random.rand(2, 3)


In [59]:
a

array([[0.19121796, 0.7711476 , 0.14653424],
       [0.6116275 , 0.69825421, 0.49705989]])

In [60]:
np.random.rand?


In [61]:
np.random.randint(5, 100, (5, 5))


array([[12, 19,  7, 44, 97],
       [10, 74, 82, 38, 46],
       [40,  9, 79, 48, 91],
       [ 7, 34, 98, 20, 27],
       [60, 50, 18, 32, 70]])

In [62]:
arr = np.array([1,2,3,4,5,6,7])


In [63]:
element = np.random.choice(arr)


In [64]:
element

1

In [65]:
np.min(a, axis = 1)


array([0.14653424, 0.49705989])

In [66]:
a.shape

(2, 3)

In [67]:
u = np.mean(c)
std_dev = np.sqrt(np.mean(abs(c - u)**2))

In [68]:
u = np.mean(c)
std_dev = np.sqrt(np.mean(abs(c-u)**2))

In [69]:
std_dev


0.0